title: <p align="center"> Zeeshan Amber </p>
logo: /assets/img/profile_pic.png
description:
  <p align="center">
    <a href="https://www.linkedin.com/in/zeeshan-amber-65a52144/">LinkedIn</a> |
    <a href="https://github.com/zeeamber">GitHub</a>
    
    <br>
      I'm a software engineer with 9 years of experience, currently working in VMware.
      I'm a technology enthusiast. Machine learning and Artificial intelligence are new set of skills I'm adding into my portfolio.
    <br>
  </p>

theme: jekyll-theme-minimal
